### ISSUE TITLE
IPv6 cannot be resolved

### ISSUE THREAD

**Issue by MagicstMagoo** [shenghuo2/mc_status_plugin_zhenxunbot#1]
当远程的Minecraft服务器处于纯 IPv6 网络环境下,无法通过抓取获取服务器状态

当阿里云DNS中`AAAA`记录值为`fe80::29ca:50a8:1369:eb67%7` <-示例
向真寻发送查询指令`mc example.magicst.cn`

图反结果为
![286081187-3450949617-05F107633FDE6A043D19945382EE0C6E](https://user-images.githubusercontent.com/96295450/198780101-367694d3-451f-446a-ad32-c07772bc320b.png)

**Comment by MagicstMagoo** [comment]
`mcstatus`中的IPv6解析在部分机器上无法正常工作🤔

**Comment by shenghuo2** [comment]
mcstatus模块的解析问题，不知道怎么解决
这个模块本身是有srv解析功能的，但是百度云的dns有大病，我就找了个dns解析网站然后写了个爬虫
所以虽然但是先咕咕咕

**Comment by MagicstMagoo** [comment]
> mcstatus模块的解析问题，不知道怎么解决 这个模块本身是有srv解析功能的，但是百度云的dns有大病，我就找了个dns解析网站然后写了个爬虫 所以虽然但是先咕咕咕

到时候我再看看怎么改((((
